audit_header: false
title: Long Island Real Estate Video Blog with Donovan Brothers Realty Inc.
description: Our mission at Donovan Brothers Realty Inc. is to be your best resource for Long Island real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The Donovan Brothers Realty Inc., your professional Long Island Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Karen and Joe Donovan
  title:
  license_number:
  about_markdown: |
    Our Goal is to Help Long Island Buyers & Sellers Realize their Real Estate Dreams!

    The Team members at Donovan Brothers Realty Inc. are local residents who are happy to listen to your requests and leave no stone unturned to help you acheive results. "Your Real Estate Needs Are Our Concern"
  brand: Donovan Brothers Realty Inc.
  brokerage:
  market: Long Island
  address: 211 Newbridge Rd, Hicksville, NY 11801
  phone: 516-822-1222
  phone_type:
  phone2:
  phone2_type:
  email: Karen@homesbydonovan.com
  url: http://www.searchmlslongisland.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: http://www.longislandinstantvalue.com/
  second_CTA_text: Home Search
  second_CTA_URL: http://www.longislandhomeslist.com/
  third_CTA_text: Let's Meet
  third_CTA_URL: /meeting/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your Long Island Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: http://www.longislandinstantvalue.com/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a Long Island Home?"
    CTA_text2: "Search the entire MLS for your Long Island home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: http://www.longislandhomeslist.com/

third_sidebar_CTA:
  - CTA_image_path3: /img/cta-images/003.jpg
    CTA_title3: "Interested in a career in real estate?"
    CTA_text3: "Set up a Skype or Coffee Meeting."
    CTA_link_text3: "Let's meet!"
    CTA_url3: /meeting/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/pages/Donovan-Brothers-Realty-Inc/202283449837871
  linkedin_url: https://www.linkedin.com/pub/karen-donovan/27/1a9/657
  youtube_url: https://www.youtube.com/channel/UCp3vS-5dLahweg0AKRDPeYQ
  twitter_url: http://www.twitter.com/donovanrealty
  instagram_url:
  pinterest_url:
  zillow_url: http://www.zillow.com/profile/Karen-Donovan/
  trulia_url: http://www.trulia.com/profile/karen-donovan-agent-11801-230122/overview
  yelp_url: http://www.yelp.com/biz/donovan-brothers-realty-inc-hicksville
  podcast_url: https://itunes.apple.com/us/podcast/long-island-real-estate-podcast/id1039516369?mt=2

podcast:
  title: 'Long Island Real Estate Podcast with Karen and Joe Donovan'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the Long Island Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from Donovan Brothers Realty Inc. - your professional Long Island Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in Long Island, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Karen and Joe Donovan'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Long Island Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#3099C8'
  theme_color: '#4d4d4d'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: '#ffffff'

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
